### ISSUE TITLE
Managing this module.

### ISSUE THREAD

**Issue by tek0011** [dell-asm/dell-compellent#42]
Since you are running this via API / CompCU calls, how do you manage issues, reports, and facts?

I ask because this method is typically against Puppets general suggested use.  If you send a call to the SCOS to create a volume, and the SCOS errors, are you retrieving the results?  How do you know what failed on the SCOS?

How do you get accurate reports back if you are leaving the scope of puppet on each call to SCOS?
How are facts handled, in order to determine if your module actually needs to do something?

Curious.

Thanks.

**Comment by ubellavance** [comment]
Not sure if it's still of interest, but the module could do a show before doing anything to know if the object already exist.
